### ISSUE TITLE
Error when DataBase is Specified in Config

### ISSUE THREAD

**Issue by dcaf-mocha** [fergusstrange/embedded-postgres#101]
`timed out waiting for database to become available` the following error consistently gets returned when trying to start the DB. This only happens when passing a custom database name in the config. 

example
```go
	dbName := "test_" + RandStringRunes(5)
	port, err := freeport.GetFreePort()
	if err != nil {
		t.Fatal(err)
	}
	user, password := "postgres", "postgres"
	database := embeddedpostgres.NewDatabase(embeddedpostgres.DefaultConfig().
		Username(user).
		Password(password).
		Port(uint32(port)).
		Version(embeddedpostgres.V14).
		Database(dbName).
		Logger(nil))
```

commenting out the custom database allows the db to be started up without time-ing out.

**Comment by fergusstrange** [comment]
Are you calling `database.Start()` at any point?
