### ISSUE TITLE
Expose an interface to retrieve binaries from non-network sources

### ISSUE THREAD

**Issue by voxeljorge** [fergusstrange/embedded-postgres#103]
I'd like to run some tests using embedded-postgres in an environment which runs tests under network isolation. It should be possible to pre-fetch the requisite binary distributions and then provide them to embedded postgres on disk rather than only via the network.

Looking at the current interfaces, perhaps a remote download interface could be exposed to allow for a custom downloader implementation to be provided which only fetches from a local disk cache rather than from the internet.

**Comment by fergusstrange** [comment]
I _think_ [this](https://github.com/fergusstrange/embedded-postgres/blob/9c9e366a34abd50f5c1b8dbfa4df01a7bca8c5d8/embedded_postgres_test.go#L566) might what you are after?

Let me know if not.

**Comment by voxeljorge** [comment]
Sort of, as it is this is a little hard to use. If I wanted it bundle a specific binary of postgres this would work, it would be nice to be able to reuse the already existing unarchiving logic.

The interface as it stands requires the user to download, unpack and place postgres in the right spot and handle cleaning up after we are done. What would be much more practical would be for the user to hand the jar over and have this library still handle unpacking/etc.

**Comment by fergusstrange** [comment]
The unpacking logic and remote fetch logic are really specific to the way Zonky has packaged up the binaries for us to use.

Without spending a fair amount of time separating it all out your best bet might be utilising `BinariesPath` and RuntimePath` and then putting a wrapper around your code that does this extraction for you.

**Comment by voxeljorge** [comment]
That's what I mean, you're just downloading these exact jars I don't want to download anything else, I'd just like to be able to prefetch those files some other way and then hand them to the library.

**Comment by voxeljorge** [comment]
To put it another way, we'd actually just be replicating the download logic that is in this library already. We'd like to use the exact same Zonky packages, we just would like to perform the actual download at some time well before the build/test run actually happens. This allows us to do things like checksum the files to help defend against supply chain attacks, and run build/test under network isolation so we can confirm that tests which should not use external network do not.

The current API is somewhat all-or-nothing, either you perform the download while the tests run or you do all of the setup manually. If we were able to re-use the download code and just pass one of these files directly to the library then there would really only be minimal manual setup still, which would be very convenient and would seem to fit with the purpose here. I can think of two ways that are probably simple to do this:

1) Provide a middleware-style API that fetches a postgres binary package given an HTTP url
2) Provide an api to override the HTTP client used by this library to download the package.

I'm sure there are other ways as well, I haven't really looked all that closely at the download code here. Either way thanks for publishing a helpful library.
