### ISSUE TITLE
List of all supported versions? - From Maven?

### ISSUE THREAD

**Issue by SamuelMarks** [fergusstrange/embedded-postgres#106]
Supported versions are available here: https://mvnrepository.com/artifact/io.zonky.test.postgres/embedded-postgres-binaries-bom

Considering we're in a AOT compiled language, I want to write a CLI that:

- Lists all installable PostgreSQL versions [that work on current OS];
- List all installed PostgreSQL versions;
- Installs specific version (e.g., `15` to install latest 15 version or `15.2.0` for specific version or `latest` for latest)

Now it would be nice if the CLI worked either without any HTTP calls required for it to fail with "version not available" error, which could be done by generate a large list | # of vars like: https://github.com/fergusstrange/embedded-postgres/blob/baa0dbf/config.go#L125-L133

OR if you had an initial large list | # of vars like above, and if the version specified by the user erred then an HTTP request to Maven would be made to see if that version is now available; and otherwise raise the "version not available" error.

EDIT: Here's an initial large list
```go
var POSTGRES_VERSIONS [117]embeddedpostgres.PostgresVersion = [117]embeddedpostgres.PostgresVersion{
	"15.2.0",
	"15.1.0",
	"15.0.0",
	"14.7.0",
	"14.6.0",
	"14.5.0",
	"14.4.0",
	"14.3.0",
	"14.2.0",
	"14.1.0",
	"14.0.0",
	"13.10.0",
	"13.9.0",
	"13.8.0",
	"13.7.0",
	"13.6.0",
	"13.5.0",
	"13.4.0",
	"13.3.0",
	"13.2.0",
	"13.1.0-1",
	"13.1.0",
	"13.0.0",
	"12.14.0",
	"12.13.0",
	"12.12.0",
	"12.11.0",
	"12.10.0",
	"12.9.0",
	"12.8.0",
	"12.7.0",
	"12.6.0",
	"12.5.0-1",
	"12.5.0",
	"12.4.0",
	"12.3.0",
	"12.2.0",
	"12.1.0-1",
	"12.1.0",
	"12.0.0",
	"11.19.0",
	"11.18.0",
	"11.17.0",
	"11.16.0",
	"11.15.0",
	"11.14.0",
	"11.13.0",
	"11.12.0",
	"11.11.0",
	"11.10.0-1",
	"11.10.0",
	"11.9.0",
	"11.8.0",
	"11.7.0",
	"11.6.0-1",
	"11.6.0",
	"11.5.0",
	"11.4.0",
	"11.3.0",
	"11.2.0",
	"11.1.0",
	"11.0.0",
	"10.23.0",
	"10.22.0",
	"10.21.0",
	"10.20.0",
	"10.19.0",
	"10.18.0",
	"10.17.0",
	"10.16.0",
	"10.15.0-1",
	"10.15.0",
	"10.14.0",
	"10.13.0",
	"10.12.0",
	"10.11.0-1",
	"10.11.0",
	"10.10.0",
	"10.9.0",
	"10.8.0",
	"10.7.0",
	"10.6.0",
	"10.5.0-1",
	"10.5.0",
	"10.4.0",
	"9.6.24",
	"9.5.25",
	"9.5.24-1",
	"9.5.24",
	"9.5.23",
	"9.5.22",
	"9.5.21",
	"9.5.20-1",
	"9.5.20",
	"9.5.19",
	"9.5.18",
	"9.5.17",
	"9.5.16",
	"9.5.15",
	"9.5.14-1",
	"9.5.14",
	"9.5.13",
	"9.4.26",
	"9.4.25-1",
	"9.4.25",
	"9.4.24",
	"9.4.23",
	"9.4.22",
	"9.4.21",
	"9.4.20",
	"9.4.19-1",
	"9.4.19",
	"9.4.18",
	"9.3.25",
	"9.3.24-1",
	"9.3.24",
	"9.3.23"}
```

EDIT: CLI is now available in working order @ https://github.com/offscale/postgres-version-manager-go

**Comment by fergusstrange** [comment]
Really awesome to see you're building out features based on this library, I'm glad it's been useful.

We're unlikely to bundle such a long list of specific versions as the intended use-case for this library is really for integration testing, and as such we aim to keep the version selections as simple as possible, with the option to provide a custom string if needed.

That said, we've left the door open with the current strategy to put a wrapper around this library with the above and do all of that logic on the outside - which it looks like you may have done already?

We are actively looking at the remote fetch logic and seeing if this could be made into a middleware style function, but it's not something we are close to making a decision on yet.

If there are any other features you're after feel free to open an issue. All the best and good luck with the CLI!

**Comment by SamuelMarks** [comment]
Thanks I'll keep you in the loop for where it goes!

In the meantime, here's the Go logic to list supported versions:

```go
import (
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path"
	"time"

	embeddedpostgres "github.com/fergusstrange/embedded-postgres"
	cli "github.com/urfave/cli/v2"
)

type Metadata struct {
	XMLName    xml.Name `xml:"metadata"`
	Text       string   `xml:",chardata"`
	GroupId    string   `xml:"groupId"`
	ArtifactId string   `xml:"artifactId"`
	Versioning struct {
		Text     string `xml:",chardata"`
		Latest   string `xml:"latest"`
		Release  string `xml:"release"`
		Versions struct {
			Text    string   `xml:",chardata"`
			Version []string `xml:"version"`
		} `xml:"versions"`
		LastUpdated string `xml:"lastUpdated"`
	} `xml:"versioning"`
}

func main() {
	var metadata Metadata
	{
		resp, err := http.Get("https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-bom/maven-metadata.xml")
		if err != nil {
			panic(err)
		}
		defer func(Body io.ReadCloser) {
			err := Body.Close()
			if err != nil {
				panic(err)
			}
		}(resp.Body)
		body, err := io.ReadAll(resp.Body)
		if err := xml.Unmarshal(body, &metadata); err != nil {
			panic(err)
		}
	}
	for _, version := range metadata.Versioning.Versions.Version {
		fmt.Printf("\"%s\",\n", version)
	}
}
```
