### ISSUE TITLE
twirp error internal: conn closed

### ISSUE THREAD

**Issue by JasonLiuZhuoCheng** [fergusstrange/embedded-postgres#107]
Trying to replace my team's testing db with embedded postgres. There are probably around 200 tests within the package, and when I use embedded postgres as the testing db, some of the tests passed, yet some of the tests are getting `conn closed` error.  I tried setting the parallel number to 1 and still doesn't fix the problem. Any thoughts? Will this [pr](https://github.com/fergusstrange/embedded-postgres/pull/102) solve this issue?  When I spectate the db during the tests were running, only around 10 connections were found using query like `SELECT count(*) FROM pg_stat_activity;`, so I am very confused why 100 connection is not enough for my use case.

**Comment by fergusstrange** [comment]
I suspect this is a different issue, and lies around how you are starting and stopping Postgres between tests.

Are you creating a single instance of `embeddedpostgres.NewDatabase()` per test and calling `Start()` and `Stop()` per test?
