### ISSUE TITLE
Add custom logger for postgres output

### ISSUE THREAD

**Issue by fergusstrange** [fergusstrange/embedded-postgres#11]

**Comment by hasibulhsn** [comment]
Any plan to do that soon?
The postgres output is messing up my test output in verbose mode.

**Comment by fergusstrange** [comment]
Hi @hsblhsn,

The project is open for pull requests to add this feature if you fancy having a crack, otherwise I will try to look into something in the next few weeks and loop you in for comment.

Thanks
