### ISSUE TITLE
Getting 'creating directory /Users/MyUser/.embedded-postgres-go/extracted/data ... initdb: error: could not create directory "/Users/MyUser/.embedded-postgres-go/extracted/data": File exists' when running tests that use embedded postgres in parallel

### ISSUE THREAD

**Issue by manuelarte** [fergusstrange/embedded-postgres#110]
Hi,

I am running some go tests in different packages, and they both use embedded postgres. The issue is that I get:

`creating directory /Users/MyUser/.embedded-postgres-go/extracted/data ... initdb: error: could not create directory "/Users/MyUser/.embedded-postgres-go/extracted/data": File exists`

Is there any way to fix this?

I tried by changing the runtimepath and it works, but I want to make sure this is a "proper" solution. Also, is the runtime path clean after the tests if I change the path?

**Comment by fergusstrange** [comment]
Hey @manuelarte this is actually an [outstanding issue](https://github.com/fergusstrange/embedded-postgres/issues/96) which we have some code for that I'm hoping to get merged in within the next few weeks.

I'll ping the above issue when it's ready for you to test. Closing this for now as a duplicate.
