### ISSUE TITLE
Absolutely not concurrency-safe

### ISSUE THREAD

**Issue by karelbilek** [fergusstrange/embedded-postgres#112]
This is absolutely not concurrency-safe and I keep tripping over various bugs all over the place when I try to run more postgresses at the same time.

I cannot even run one postgres easily and create more databases.

Are there plans to tackle this?

**Comment by karelbilek** [comment]
There is this fork that seems to fix a lot of that

https://github.com/PaddleHQ/embedded-postgres/tree/sync

ping @alecsammon

**Comment by karelbilek** [comment]
ah even that fork fails, as the cache is still shared

**Comment by fergusstrange** [comment]
Hey @karelbilek we have some code we think will tackle this issue that I'm hoping to merge over the coming weeks. I'll post updates to [this issue](https://github.com/fergusstrange/embedded-postgres/issues/96) when that happens.

Regarding creating a secondary database, you should be able to achieve this with CLI tools once the initial one is spun up or using a DDL statement such as `CREATE DATABASE mydatabase` before you start your tests.
