### ISSUE TITLE
CLI release for PostgreSQL version manager [embedding your project]

### ISSUE THREAD

**Issue by SamuelMarks** [fergusstrange/embedded-postgres#114]
I built a thing

https://github.com/offscale/postgres-version-manager-go

Happy to contribute any changes back to your library. Also if you want to make everything I use public then I'll remove the code duplication and depend directly on your library.

Anyway I hope others find this CLI variant useful =)

**Comment by fergusstrange** [comment]
Very neat and something I was looking to build one day myself! Great work!
