### ISSUE TITLE
how to change r/w permission?

### ISSUE THREAD

**Issue by Snax1210** [fergusstrange/embedded-postgres#118]
When I run this library in the windows environment, if it is installed on C: drive, it will cause the initialization database to fail, because the files in C: drive cannot be read and written, how to change the running permission?

**Comment by Snax1210** [comment]
The error log is :


2023/06/20 11:42:06 pg server error, message is : %!s(MISSING)unable to extract postgres archive C:\Users\***\.embedded-postgres-go\embedded-postgres-binaries-windows-amd64-13.11.0.txz to C:\Program Files\diaoyucheng/pg/binary, if running parallel tests, configure RuntimePath to isolate testing directories, CreateFile C:\Program Files\diaoyucheng\pg: The system cannot find the file specified.
panic: pg server error, message is : %!s(MISSING)unable to extract postgres archive C:\Users\****\.embedded-postgres-go\embedded-postgres-binaries-windows-amd64-13.11.0.txz to C:\Program Files\diaoyucheng/pg/binary, if running parallel tests, configure RuntimePath to isolate testing directories, CreateFile C:\Program Files\diaoyucheng\pg: The system cannot find the file specified.

**Comment by Snax1210** [comment]
btw, how to set the initialization path that contains Chinese characters

**Comment by fergusstrange** [comment]
What exact parameters did you use to invoke embedded-postgres?

**Comment by Snax1210** [comment]
postgres := embeddedPostgres.NewDatabase(embeddedPostgres.DefaultConfig().
		Username(datasource.Username).
		Password(datasource.Password).
		Database(datasource.Dbname).
		Version(embeddedPostgres.V13).
		BinariesPath(pgRootPath + constant.BinariesPath).
		DataPath(pgRootPath + constant.DbTmpDir).
		Port(uint32(port)).
		Logger(loggerWrapper).
		StartTimeout(45 * time.Second))
	pgErr := postgres.Start()

**Comment by Snax1210** [comment]
thx

**Comment by fergusstrange** [comment]
Looks like you might not be joining your paths together correctly. Try using [`path.Join`](https://pkg.go.dev/path#example-Join) instead of `+`.

I'm not sure what the values of `constant.DbTmpDir`, `constant.BinariesPath` and `pgRootPath` are but you should also be using `\` path join on windows.

**Comment by Snax1210** [comment]
thx,  I'll give it a try.
