### ISSUE TITLE
Jar unzip fails when server does not set ContentLength

### ISSUE THREAD

**Issue by djcass44** [fergusstrange/embedded-postgres#123]
In my environment we are behind a corporate proxy and have to pull Jars through a cache service (think Artifactory or Nexus). This service returns data using chunked encoding and therefore doesn't set the `Content-Length` header.

This library [depends on ContentLength being set](https://github.com/fergusstrange/embedded-postgres/blob/master/remote_fetch.go#L78). If not set, Go sets it to `-1` which causes the `zip.NewReader` call to fail instantly.

It should be easily fixable by simply using `len(bodyBytes)` when `contentLength < 0`. I will open an MR alongside this issue.

**Comment by fergusstrange** [comment]
Released with [v1.25.0](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.25.0)
