### ISSUE TITLE
Why erased RuntimePath directory?

### ISSUE THREAD

**Issue by pobearm** [fergusstrange/embedded-postgres#141]
The RuntimePath directory is erased and recreated at each Start().
In func (ep *EmbeddedPostgres) Start(): 
```go
if err := os.RemoveAll(ep.config.runtimePath); err != nil {
	return fmt.Errorf("unable to clean up runtime directory %s with error: %s", ep.config.runtimePath, err)

}
```
Why we earse this directory every time Start? It cause very slow when starting our app.
Any ideas of use check instead of erase? Or add some options.

**Comment by fergusstrange** [comment]
Hey @pobearm this is by design to ensure an absolutely clean instance of Postgres every time. We do this because the tool is intended as a testing tool rather than for persisting data.

What is your use case for context?
