### ISSUE TITLE
StartParameters don't work on Windows

### ISSUE THREAD

**Issue by hugodutka** [fergusstrange/embedded-postgres#145]
Each parameter [is enclosed in single quotes](https://github.com/fergusstrange/embedded-postgres/blob/06253c602c124d13b972ed0dc7ca181923a1ee36/embedded_postgres.go#L200), which the shell on Windows [treats as regular characters](https://stackoverflow.com/a/51090074) rather than string delimiters. Embedded postgres then fails to start with:

```
waiting for server to start....2024-10-30 19:27:34.938 GMT [5368] FATAL:  invalid value for parameter "max_connections": "'1000'"
 stopped waiting
pg_ctl: could not start server
Examine the log output.
panic: could not start postgres using C:\Users\RUNNER~1\AppData\Local\Temp\coder-test-postgres\bin\bin\pg_ctl start -w -D C:\Users\RUNNER~1\AppData\Local\Temp\coder-test-postgres\data -o -p 5432 -c max_connections='1000':
```

As a workaround, one can use `ALTER SYSTEM SET` SQL queries for now.

**Comment by hugodutka** [comment]
@fergusstrange Would you be open to accepting a PR to fix this issue?

**Comment by fergusstrange** [comment]
Absolutely @hugodutka, I'm suprised this hasn't cropped up before!

If you could add some level of coverage in here https://github.com/fergusstrange/embedded-postgres/blob/master/platform-test/platform_test.go then these should automatically run (and fail on windows).

That should be enough to prove the value and fix suggested encoding method here https://github.com/fergusstrange/embedded-postgres/blob/7c0ced30394508c74e955df154e4ee7c7b560b30/embedded_postgres.go#L205

Let me know how you get on?

Cheers

**Comment by fergusstrange** [comment]
Release @ [v1.30.0](https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.30.0) thanks!
