### ISSUE TITLE
Unable to run in official docker golang:1.15

### ISSUE THREAD

**Issue by thetruechar** [fergusstrange/embedded-postgres#17]
unable to init database using: /root/.embedded-postgres-go/extracted/bin/initdb -A password -U postgres -D /root/.embedded-postgres-go/extracted/data --pwfile=/root/.embedded-postgres-go/extracted/pwfile

**Comment by fergusstrange** [comment]
Hi @thetruechar, thanks for takign the time to report an issue.

Can you be specific about the error you receive? I suspect this could be todo with file permissions?

Thanks

**Comment by thetruechar** [comment]
FROM golang:1.15
RUN go test ./...

it will produce the error, it probably caused by the root user in the container.

**Comment by fergusstrange** [comment]
Hi @thetruechar,

Postgres doesn't actually support being run as the root user. A snippet from the [documentation](https://www.postgresql.org/docs/13/app-initdb.html) is as follows:

> initdb must be run as the user that will own the server process, because the server needs to have access to the files and directories that initdb creates. Since the server cannot be run as root, you must not run initdb as root either. (It will in fact refuse to do so.)

As a course of best practice I'd suggest running your tests as a non root user as well?

Finally if you still believe some functionality around adding `sudo` in front of the `initDB` functionality then feel free to open a pull request with this as a custom non default option? Perhaps something akin to the following...

```
postgres := NewDatabase(DefaultConfig().
            Version(V12).
            RunWithElevatedPermissions
```

This would need to do some reasonable checking to ensure the correct permissions were granted based on every supported operating system.

Thanks again for taking the time to raise this issue, and best of luck coding!

**Comment by thetruechar** [comment]
So how can we use this in docker based ci system?

**Comment by fergusstrange** [comment]
I'd recommend building a custom image on top of the official GoLang image with a non privileged user. I've tested the below docker file which you can build and reuse against this repositories tests all looking good.

```
FROM golang:1.15

RUN addgroup appgroup
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "appgroup" \
    --no-create-home \
    "appuser"

USER appuser
WORKDIR /go/src/yourrepo
```

Build with `docker build -t golang-ci .`

Run your tests with docker run `docker run -it -v $(pwd):/go/src/yourrepo golang-ci go test -v ./...`

Best of luck and let me know if this resolves your issues!

Thanks
