### ISSUE TITLE
Better support for using as application database

### ISSUE THREAD

**Issue by bearsh** [fergusstrange/embedded-postgres#18]
I just stumbled on this project which is kind of what I've been looking for a long to easily use postgres without caring about the installation of the server.

But there are some points which are rather unfortunate to use the lib as-is in a project other than for tests.
1. Start method is a monolith  
   - db data directory is erased on each start
   - db is initialized each time
   - db is created each time
2. db data is in `RuntimePath`
3. not infrastructure to test if a db data directory is already available

@fergusstrange would you accept PRs which change the above mentioned behavior? I would like to see them integrated in this project rather then maintain a fork of this lib...

**Comment by fergusstrange** [comment]
Absolutely. Have left a few comments on PR. Keen to minimise configuration to keep the project as simple as possible but this would definitely help out a few of our existing and future users.

Thanks

**Comment by fergusstrange** [comment]
Thanks for all your work @bearsh. I've snapped a release @ https://github.com/fergusstrange/embedded-postgres/releases/tag/v1.4.0
