### ISSUE TITLE
Postgres extensions

### ISSUE THREAD

**Issue by ehsanonline** [fergusstrange/embedded-postgres#21]
Is it possible to install and use Postgres extensions? if yes, how? I need [AGE](https://github.com/apache/incubator-age) specifically.

**Comment by fergusstrange** [comment]
Hi @ehsanonline,

The database starts and the runtime path is accessible so it would definitely be possible to move precompiled binaries into this location.

This isn't something I think we'd support in the short term but absolutely something that should be considered as part of a post runtime installation stage. In this case I'd imagine it acting like a generic plugin phase that you could provide the binaries per operating system. Do you have a source for the precompiled binaries for AGE?

Is see you've reopened an issue at https://github.com/zonkyio/embedded-postgres-binaries/issues/6. This may be the quickest path to resolution but I'll keep an eye in the meantime!
