### ISSUE TITLE
Allow specifying a custom RemoteFetchStrategy/CacheLocator ?

### ISSUE THREAD

**Issue by mbfr** [fergusstrange/embedded-postgres#35]
Not sure if I'm missing something from reading the source code, but it seems that although these two types are exported it's impossible to actually use a custom implementation because these fields are private on the EmbeddedPostgres struct.

My use case is that I want to be able to use a pre-downloaded postgres binary (or at least download from a different URL that I control).

**Comment by fergusstrange** [comment]
Hey @mbfr, thanks for raising this. You are correct, this is actually only really exposed internally for testability.

Happy for you to raise a PR with this as a config value that overrides the default config, as long as the API remains backwards compatible. For your use case it seems like that should cover it?
