### ISSUE TITLE
Upgrade to a newer version of Go

### ISSUE THREAD

**Issue by naveensrinivasan** [fergusstrange/embedded-postgres#44]
As of writing, this issue go `1.17` is the latest version.

Go does support version 1 version from the release version which is `1.16` 

https://github.com/fergusstrange/embedded-postgres/blob/2eb4b671b274e784601b1c0f708be956b9c7731a/go.mod#L3

**Comment by fergusstrange** [comment]
@naveensrinivasan we are aiming to support back a number of GoLang versions from the currently released. As it stands we support approximately 3 years of GoLang releases, and will probably aim to keep this the same.

Upgrading GoLang versions would only offer more language features which we are not desperate for currently as well. When generics is made available we will reconsider this and likely release a major version.

Thanks
