### ISSUE TITLE
Running multiple tests in parallel causes an error

### ISSUE THREAD

**Issue by nathanfranke** [fergusstrange/embedded-postgres#45]
```
$ go test ./...
ok      github.com/nathanfranke/my-project/dummy1 2.171s
--- FAIL: TestDummy (0.13s)
    dummy_test.go:81: creating embedded database...
    dummy_test.go:84: unable to extract postgres archive /home/nathan/.embedded-postgres-go/embedded-postgres-binaries-linux-amd64-12.8.0.txz to /home/nathan/.embedded-postgres-go/extracted
FAIL
FAIL    github.com/nathanfranke/my-project/dummy2 0.130s
FAIL
```

**Comment by fergusstrange** [comment]
Hey @nathanfranke,

This is possible however the tests would need to either run with different port and runtime directory as [demonstrated here](https://github.com/fergusstrange/embedded-postgres/pull/46/files) or if you wish to actually reuse the same Postgres instance you'll need to start and stop separately from your test flow doing something like [this](https://github.com/fergusstrange/embedded-postgres/commit/df3fffd805d4fb81869980369d30281624e65d9c#diff-d9806270eec56a5871dcae5b06b25070c71b84a1270d649db67a2484f4371bb8R67).

Let me know how you go?

Thanks

**Comment by nathanfranke** [comment]
Currently I'm using -p 1 to run the tests in series. However it would be nice if the directory used is random to avoid this issue

**Comment by fergusstrange** [comment]
You should be able to achieve this already with something like

```
dir, err := ioutil.TempDir("", "whatever_prefix_you_want")
if err != nil {
    panic(err)
}
database := NewDatabase(DefaultConfig().Port(rand.Uint32()).RuntimePath(dir))
```

This flexible config allows you to maintain the logic yourself. This is something we probably won't be looking to add to the library logic itself.

Thanks
