### ISSUE TITLE
Unable to test with github actions

### ISSUE THREAD

**Issue by glserranv** [fergusstrange/embedded-postgres#53]
I have set up in my local some test and been able to run them. Works fine. Now I am trying to run them on github actions but I get an error. I have check the code it seems an issue when trying to get the .txz file inside the jar. 

I get this error ` panic: error fetching postgres: cannot find binary in archive retrieved from https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.8.0/embedded-postgres-binaries-linux-amd64-12.8.0.jar [recovered]
	panic: error fetching postgres: cannot find binary in archive retrieved from https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.8.0/embedded-postgres-binaries-linux-amd64-12.8.0.jar
` 

This is my github actions yaml.

```name: unit-test
on: [pull_request,push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.}
      - go get -u github.com/fergusstrange/embedded-postgres
      - run: go test -v
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_NAME: postgres
          DB_PASSWORD: postgres
          LC_CTYPE: UTF-8
```

I have no idea on what can be wrong. I have tested that the url can be downloaded and that seems to be ok. I have checked the actions you define in this proyect to test it and it doesn´t look very different from mine.

**Comment by fergusstrange** [comment]
Hi @glserranv,

Are you still seeing these issues? I've not been able to replicate the issue you're seeing above but it does suggest we could do with some better error messaging in general which I will take up as a task over the coming releases.

I've created a repo and produced a green build which you can see here: https://github.com/fergusstrange/test-project/actions

This has highlighted that providing the `LC_CTYPE` environment variable failed the build a few times. This produced a different error from above however which I will look into separately.

If you can provide us a snippet of the code you're actually running or a link to the repo I may be able to help more!

Thanks

**Comment by glserranv** [comment]
Hi ,I was able to solve it. I am not sure what the issue was but I got this error by running this before my test `go get -u github.com/fergusstrange/embedded-postgres` However my db was not being instantiated and I solved it by adding env variables.

`LC_ALL: en_US.UTF-8
  LC_CTYPE: en_US.UTF-8`
