### ISSUE TITLE
Cannot find binary in archive 

### ISSUE THREAD

**Issue by survivorbat** [fergusstrange/embedded-postgres#54]
Hey all, stumbled upon this repository and decided to give it a try.

Unfortunately the following snippet does not seem to work me.

```go
pg := embeddedpostgres.NewDatabase()

if err := pg.Start(); err != nil {
  t.Error(err)
  return
}

defer pg.Stop()
```

This gives me the error `error fetching postgres: cannot find binary in archive retrieved from https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/12.8.0/embedded-postgres-binaries-linux-amd64-12.8.0.jar`

`go version` gives me: `go version go1.17.1 linux/amd64` and I'm running Ubuntu 20.04.01 with kernel 5.8.0-23-generic.

Am I doing something wrong?

**Comment by khaledious** [comment]
I am having the same issue on windows, ` test panicked: error fetching postgres: cannot find binary in archive retrieved from https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-windows-amd64/12.8.0/embedded-postgres-binaries-windows-amd64-12.8.0.jar`

**Comment by khaledious** [comment]
This might just be a poor error disc,
```
downloadedArchive, err := zipFile.Read()
if err != nil {
	return errorExtractingBinary(downloadURL)
}
```
Looks like it is thrown if there are any errors reading any of the files.

**Comment by survivorbat** [comment]
@fergusstrange @naveensrinivasan do you perhaps know why this is happening? Can I do something to fix this?

**Comment by mikes-br** [comment]
I think you need to set your Binaries Path explicitly on non-linux OSes. The defaults use $USER_HOME which works on Linux but not Windows or Darwin by default

**Comment by mikes-br** [comment]
I got past this problem by creating a separate Binaries Path from the Runtime Path, and then manually extracting the binaries to the location specified as the binaries path. I'm unfortunately still screwed because I have an M1 Macbook with Apple Silicon and there aren't binaries on mavencentral for my architecture. I'm trying to figure out how to build my own postgres into my cache forlder now. But if you construct the binaries path manually you should be fine as long as you're not on Apple Silicon

**Comment by gedw99** [comment]
works on Intel mac using basic example.

**Comment by gedw99** [comment]
AMR MAC is here: https://www.postgresql.org/download/macosx/

**Comment by gedw99** [comment]
> back



> I think you need to set your Binaries Path explicitly on non-linux OSes. The defaults use $USER_HOME which works on Linux but not Windows or Darwin by default. Doing some testing locally. Will report back if I make progress

find my $USER_HOME on intel mac. But not on arm mec ?

**Comment by gedw99** [comment]
So its looks like eventually we will get universal binaries for mac..

SO the golang code that downloads might have to incorporate the logic of it:
quasi example: 
https://github.com/zonkyio/embedded-postgres/commit/ce6256ea4fced93b378a0f92cdc54f92a35b80cc

**Comment by survivorbat** [comment]
I've fixed it in my own fork by iterating over the files in the archive and just unpacking the file with the '.txz' suffix. The real error that occurs - which is hidden behind the pretty one- is 'EOF'. This bandage fix seems to work on linux and mac so far. The unpacking is where the issue occurs.

@mikes-br I'm sorry I don't understand what you mean exactly, I'm using Ubuntu (Linux) which according to your answer should not have issues. I might be misinterpreting your reply.

**Comment by fergusstrange** [comment]
Hi all,

Seems like there's a few things going on in this thread, but doing my best to unpack:

- Better logging on extraction failure
- Look into support for better logging on new Mac ARM, with rosetta emulation support by default
- Longer term support for Mac ARM when the packages are available on Maven
- Some issues which I'm struggling to reproduce around conflicting binaries path and the default user home on Windows?

Once I can get these all ironed out, and potentially moved into separate issues we can start putting together some code to solve them. Does this list look complete and finally is there anyone keen to take any of the above items on themselves?

Thanks all

**Comment by mikes-br** [comment]
> @mikes-br I'm sorry I don't understand what you mean exactly, I'm using Ubuntu (Linux) which according to your answer should not have issues. I might be misinterpreting your reply.

Sorry @survivorbat I was replying to the Windows user. You're correct that $USER_HOME should work on most linux distributions and that my answer wasn't helpful to you the o.p.

**Comment by gedw99** [comment]
thanks for picking up on this @fergusstrange 

On intel mac it works, but in my code i had issues with defer in terms of shutting down the DB cleanly.

**Comment by survivorbat** [comment]
Hey all, the latest problem fixed the issue, it now downloads like it's supposed to.

If the work items described above are picked up, this issue can be closed. Thanks for the comments.

**Comment by gedw99** [comment]
Thanks for the quick turnaround.

will give it a try on Intel Mac

Should I raise a different issue regarding Arm Mac ? So we can isolate the jumbled up things raised in this issue .

**Comment by gedw99** [comment]
Issue isolated to Intel and Arm MAC is now here: https://github.com/fergusstrange/embedded-postgres/issues/56

hope that’s ok

**Comment by survivorbat** [comment]
Closing this issue since the issue is fixed
