### ISSUE TITLE
Description is misleading

### ISSUE THREAD

**Issue by mihaiav** [fergusstrange/embedded-postgres#60]
This is not a an embedded, in-memory postgres database in Go. It's a Java database with a Go wrapper.

**Comment by fergusstrange** [comment]
Hi @mihaiav this is not actually the case, there is no java involved at all.

It is a real Postgres database, running natively on your machine. If you pause the app you will see the process running in the background.

There may be some confusion as we download `.jar` files, but these are simply `.zip` files with our Postgres native dependencies inside them. You can view these here: https://mvnrepository.com/artifact/io.zonky.test.postgres/embedded-postgres-binaries-bom.

Open to suggestions for a better description, but most of the wording is following the approach used by the projects that inspired this one.
