### ISSUE TITLE
Specify encoding while init database

### ISSUE THREAD

**Issue by DisinS** [fergusstrange/embedded-postgres#74]
Is it possible to define the database encoding via arguments in the configuration?

**Comment by fergusstrange** [comment]
Not currently but, definitely be open to adding this feature via a pull request if necessary. I can investigate but it may take some time.

As a work around you may be able to create your secondary database once the init process has completed.

**Comment by DisinS** [comment]
It would be awesome to have it. The whole package is great and that is the only thing that I have a problem with.

**Comment by zzzFelix** [comment]
I'm also interested in having this feature and would like to work on it.

Btw another possible workaround is to specify a locale. e.g. `en_US` changes the encoding from `SQL_ASCII` to `UTF8`.
