### ISSUE TITLE
Any logger example to only process stderr?

### ISSUE THREAD

**Issue by sneko** [fergusstrange/embedded-postgres#82]
Hi,

At first use I saw a lot of logs in my tests due to the DB setup so I decided to discard them with:
```
embeddedpostgres.DefaultConfig().Logger(ioutil.Discard)
```

Quick questions:
- is there any reason to maintain them since the client errors should give some insights in case of failures?
- if so, do you have a logger example where it would just catch errors from the server? Like catching only `stderr` and not `stdout`? But I'm not sure it's possible since the logger is a `io.Writer` without more information on the original output channel

Thank you,

**Comment by fergusstrange** [comment]
Hey currently we capture all content from stdout and stderr as you can see [here](https://github.com/fergusstrange/embedded-postgres/blob/7bf3aab2dca3964165ded64585e2516791c88876/embedded_postgres.go#L187).

Short term quickest solution might be to provide your own logger interface that filters out lines that don't start with `ERROR:`.

Longer term I can look into adding a separate logger config per output, but this isn't a burning priority right now for us.

Thanks
