### ISSUE TITLE
Can't change `postgres.conf` values

### ISSUE THREAD

**Issue by subhan-nadeem** [fergusstrange/embedded-postgres#94]
I want to override in the `MAX_CONNECTIONS` variable which is located in `RuntimePath/postgresql.conf`. The problem is, this value needs to be overridden prior to the DB process starting in order to take effect. `postgres.Start()` clears `RuntimePath` directory, which doesn't allow a custom `postgresql.conf` to be injected. There's also no restart mechanism that would utilize the same `postgresql.conf` file without wiping `RuntimePath`.

**Comment by fergusstrange** [comment]
Hey @subhan-nadeem, apologies for the delay in responding.

This sounds like a generic `beforeStart()` sort of method would be useful, which took an anonymous function? I'm a bit short on time but if you think you could do something around this I'd welcome a pull request with the additional feature.

Cheers

**Comment by jgiles** [comment]
I added https://github.com/fergusstrange/embedded-postgres/pull/102 as a proposed fix for this issue.

It takes the approach of feeding configuration values to postgres on the command line at startup. I think that is probably easier than adding a hook for file placement (both for this library to implement and for clients to use).
